// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb-zS_90jUdX8vl6VMfkvOog8haOHfC9s',
    appId: '1:221053669302:web:bddc59851208526bd47b17',
    messagingSenderId: '221053669302',
    projectId: 'truetrace-5914d',
    authDomain: 'truetrace-5914d.firebaseapp.com',
    storageBucket: 'truetrace-5914d.firebasestorage.app',
    measurementId: 'G-X42JF3CGVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ_ZD7oqT2-RuUZdKoNmgU6P8IGa8O5jg',
    appId: '1:221053669302:android:8145c9abcf482fb8d47b17',
    messagingSenderId: '221053669302',
    projectId: 'truetrace-5914d',
    storageBucket: 'truetrace-5914d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNtbRcM1rwEqj1ac7uMDf6uBiH0Dq34sI',
    appId: '1:221053669302:ios:0eb65dff46feb725d47b17',
    messagingSenderId: '221053669302',
    projectId: 'truetrace-5914d',
    storageBucket: 'truetrace-5914d.firebasestorage.app',
    iosBundleId: 'com.example.truetraceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNtbRcM1rwEqj1ac7uMDf6uBiH0Dq34sI',
    appId: '1:221053669302:ios:0eb65dff46feb725d47b17',
    messagingSenderId: '221053669302',
    projectId: 'truetrace-5914d',
    storageBucket: 'truetrace-5914d.firebasestorage.app',
    iosBundleId: 'com.example.truetraceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb-zS_90jUdX8vl6VMfkvOog8haOHfC9s',
    appId: '1:221053669302:web:d8a646253681da8ad47b17',
    messagingSenderId: '221053669302',
    projectId: 'truetrace-5914d',
    authDomain: 'truetrace-5914d.firebaseapp.com',
    storageBucket: 'truetrace-5914d.firebasestorage.app',
    measurementId: 'G-2P017DZHRQ',
  );

}